version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: sector_db
    user: postgres
    environment:
      POSTGRES_DB: "sector-db"
      POSTGRES_USER: "sector-user"
      POSTGRES_PASSWORD: "sector-pass"
    ports:
      - 5432:5432
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    container_name: api
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/sector-db"
      DB_USER: "sector-user"
      DB_PASS: "sector-pass"
    ports:
      - 8080:8080
    depends_on:
      - postgres
  sectors-ui:
    build:
      args:
        URL_SECTOR_API: "http://127.0.0.1:8080/api/v1"
      dockerfile: Dockerfile
      context: ./sectors-ui
    container_name: sectors-ui
    ports:
      - 3000:3000
    depends_on:
      - api